# Generated by Django 4.2.3 on 2023-08-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('UNORDER', 'UNORDER'), ('ORDER', 'ORDER')], default='UNORDER', max_length=100),
        ),
    ]
