# Generated by Django 4.2.3 on 2023-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_cartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
    ]
