# Generated by Django 4.2.3 on 2023-08-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_remove_order_name_remove_order_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
